# Generated by Django 5.1.6 on 2025-02-17 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0002_alter_submission_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='score',
            field=models.DecimalField(decimal_places=1, max_digits=100.0),
        ),
    ]
