# Generated by Django 5.1.6 on 2025-02-17 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0003_alter_submission_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='score',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=100.0, null=True),
        ),
    ]
